### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Shaan18** [git-it-chan/web-design-2-project#1]
Hi Chandler,
Your site look great over all I like the aesthetics and you have  different looks for all of your pages.
In your About page your text is a little hard to read on tablet and desktop screen, if you can make it a little shorter in length  or not make it go all the way to the end of the photo, it will look better.
Great looking website tho.

**Comment by Shaan18** [comment]
@wendywarren

**Comment by git-it-chan** [comment]
My "About" page was definitely the most problematic of my 3 pages, as it was the only one I haven't adjusted with media queries (the large image sizes are definitely the culprit).

I've adjusted the image sizes and positioning so that the text isn't so squeezed in. There are now properly sized paragraphs to be viewed on a tablet/desktop device.
